# Data Checkpoint

# Name

Stephanie Patricia Anshell

# Research Question

What is the correlation between public transportation accessibility—assessed through transit stop density, service frequency, passenger volume, transit system integration, transfer ease among modes, and availability of diverse transit options—and urban crime rates (violent vs. property crimes) in major U.S. cities like Chicago and New York City from 2014 to 2021?

## Background and Prior Work

Urban planners and criminologists have long sought to answer how public transportation systems influence local crime rates, especially in major metropolitan areas. The common hypothesis is that transit accessibility can function either as a deterrent or attractor for opportunistic crimes where large crowds gather every day. By exploring the interplay between different factors researchers hope to inform evidence based transportation and policing in order to create safer and better cities. 

Several studies illustrate the complexity of this relationship. Ridgeway and MacDonald<a name="cite_ref-1"></a>[<sup>1</sup>](#cite_note-1) investigated Los Angeles Metro Rail expansions between 1988 and 2014. They leveraged major strikes as natural experiments to examine crime trends in neighborhoods that are affected by disrupted transit systems. Furthermore, they examined the effects of newly established transit access. Contrary to earlier assumptions that transit stops serve as a crime magnet, they failed to find significant impact of rail services on local crime rates.

This stands in contrast to the result Neiss<a name="cite_ref-2"></a>[<sup>2</sup>](#cite_note-2) evaluated with short term effects of the new bus line introduced in Cleveland. From this incident Neiss was able to detect a measurable uptick in property crime following the introduction of that new line. Meanwhile, Newton’s broader survey<a name="cite_ref-3"></a>[<sup>3</sup>](#cite_note-3) of crime on public transport underscored the importance of context from his observations that crimes often cluster at specific stations or nodes rather than uniformly throughout the transit system. 

Considering these findings together, it would be necessary to implement large data driven approaches that include geographic and socioeconomic conditions alongside the transit and crime metrics, to determine how public transportation contributes to changes in crime patterns. As prior works have mixed results, and focus on single cities or short term effects, This research should aim to analyze multiple major cities and long term data such that offers broader perspective on how transit accessibility affects crime rate. Through this I expect to fill the gap in the academic and policy discourse, clarifying whether certain patterns hold across diverse urban environments and its transportation.


1. <a name="cite_note-1"></a> [^](#cite_ref-1) Ridgeway, G., & MacDonald, J. (2015). Effect of Rail Transit on Crime: A Study of Los Angeles from 1988-2014. Penn Criminology Working Papers. https://crim.sas.upenn.edu/sites/default/files/2015-14.0_Ridgeway_MacDonald_RailEffect%281%29.pdf
2. <a name="cite_note-2"></a> [^](#cite_ref-2) Neiss, S. (2015). Does Public Transit Affect Crime? The Addition of a Bus Line in Cleveland, Ohio. The Journal of Economics and Politics. https://collected.jcu.edu/cgi/viewcontent.cgi?article=1003&context=jep
2. <a name="cite_note-3"></a> [^](#cite_ref-3) Newton, A. (2014). Crime on Public Transport. In Encyclopedia of Criminology and Criminal Justice (pp. 795-804). https://www.researchgate.net/publication/277327477_Crime_on_Public_Transport

### Why This Research Is Important Today

 Public transportation systems have been linked to changing crime rates for a while, but the specifics of this connection are still up for discussion. In today's fast changing urban environment, cities are working hard to develop transit networks that are safer and easier to use, all while addressing worries about crime. Efficient public transportation can improve how people move around, boost economic growth, and lessen environmental harm. However, it might also unintentionally lead to areas that draw criminal activity because of the increased foot traffic and lack of surveillance. As cities keep growing their transit systems, it's really important for urban planners, law enforcement, and lawmakers to understand this relationship. This research helps make urban mobility safer and more equitable, and it also offers valuable insights for everyone. Better transit planning can improve quality of life, lessen fear of crime, and motivate more people to use public transportation.

### Literature Review:
1. Ridgeway, G., & MacDonald, J. (2015) Effect of Rail Transit on Crime: A Study of Los Angeles from 1988-2014. Penn Criminology Working Papers. 

 Ridgeway and MacDonal examined the long term impact of Los Angeles Metro Rail expansion on neighborhood crime rates from 1988 to 2014. They analyzed crime data before and after new station openings and marked two major strikes as natural experiments to see the effect of transit accessibility on crime. Their finding suggests that public transit expansions had no significant impact on crime rates in surrounding neighborhoods. While some of their cited prior studies identified transit stops as crime hotspots, they found no evidence to back up such claims. They concluded that crime trends remained stable regardless of transit disruptions or expansions.

2. Neiss, S. (2015) Does Public Transit Affect Crime? The Addition of a Bus Line in Cleveland, Ohio. The Journal of Economics and Politics. 

 This paper investigated the short term effects of introducing a new bus line in Cleveland on local property crime rates. By analyzing data before and after the introduction of that bus line, the research found evidence suggesting that public transportation can increase crime rates in surrounding areas. Neiss noted that this conclusion is based on short term observation and recommended further assessments on long term impacts.

3. Newton, A. (2014) Crime on Public Transport. In Encyclopedia of Criminology and Criminal Justice

 This paper examines how crime concentrates and potentially specializes within and around public transport systems. Newton discusses the unique challenges in identifying crime patterns in these settings and highlights the distinct environments such as stations and vehicles where crime can occur. This work showed that crime is often concentrated at specific transit nodes rather than uniformly across the transit network. However, this work does not directly answer the research question as it was finished open ended in terms of whether public transportation works as a crime attractor with Newton stating that it depends on other aspects of such stations.

# Hypothesis

I hypothesize that higher public transportation accessibility, measured by transit stop density, service frequency, and ridership, is positively correlated with reported crime rates (both violent and property crimes) in major U.S. cities from 2014 to 2021. Specifically, I expect that areas with increased transit access will exhibit higher crime counts and that normalizing crime by ridership may reveal whether these areas experience a disproportionate number of crimes relative to the size of people present. While I acknowledge that socioeconomic factors will likely play a role in this, my analysis will focus on transit metrics and crime data.

# Data

## Data overview

For each dataset include the following information
- Dataset #1
  - Dataset Name:NYPD Arrests Data (Historic)
  - Link to the dataset: https://data.cityofnewyork.us/Public-Safety/NYPD-Arrests-Data-Historic-/8h9b-rp9u/data_preview
  - Number of observations:5725522
  - Number of variables:19
- Dataset #2 
  - Dataset Name:Chicago Crimes - 2001 to Present 
  - Link to the dataset: https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2/about_data
  - Number of observations: 8261886
  - Number of variables: 22
- Dataset #3
  - Dataset Name:MTA Subway Stations
  - Link to the dataset: https://catalog.data.gov/dataset/mta-subway-stations
  - Number of observations: 496
  - Number of variables: 19
- Dataset #4
  - Dataset Name: MTA Subway Turnstile Usage Data 
  - Link to the dataset: https://catalog.data.gov/dataset/?q=MTA+Subway+Turnstile+Usage+Data&sort=views_recent+desc&ext_location=&ext_bbox=&ext_prev_extent=
  - Number of observations:9492670
  - Number of variables: 11
- Dataset #5
  - Dataset Name:CTA - System Information - List of 'L' Stops
  - Link to the dataset: https://data.cityofchicago.org/Transportation/CTA-System-Information-List-of-L-Stops/8pix-ypme/about_data
  - Number of observations: 302
  - Number of variables: 17
- Dataset #6
  - Dataset Name: CTA - Ridership - 'L' Station Entries - Daily Totals
  - Link to the dataset: https://data.cityofchicago.org/Transportation/CTA-Ridership-L-Station-Entries-Daily-Totals/5neh-572f/data_preview
  - Number of observations: 1250303
  - Number of variables: 5

**For all these Datasets' pre-processing, I will drop any datapoint that is not within 2014 to 2022 in terms of years according to the scope of research.**




* Dataset 1: This dataset contains arrest records from New York City. Each arrest has a unique ID number (ARREST_KEY) and a date (ARREST_DATE) that might need to be changed into a proper date format. It also includes offense codes (like PD_CD, KY_CD, PD_DESC, and OFNS_DESC) that describe the type of crime. There are also demographic details, such as AGE_GROUP, PERP_SEX, and PERP_RACE, that show the ages, genders, and races of those arrested. Location information is given with (X_COORD_CD, Y_COORD_CD, Latitude, and Longitude), and there’s also a geometry field (Lon_Lat) that may need to be changed into a more useful format for mapping. In terms of pre-processing I need to fix dates format, redefine or organize categories, correct missing or wrong location details, and remove duplicate records to make sure everything is accurate and easy to analyze.

* Dataset 2: This dataset has crime incident records from Chicago. Each crime has a unique ID and Case Number to identify it. It also includes dates (Date, Updated On) and location details (Block, X Coordinate, Y Coordinate, Latitude, and Longitude) to show where the crime happened. The dataset has crime categories like Primary Type and Description, as well as true/false (yes/no) fields like Arrest whether someone was arrested and Domestic if the crime was related to domestic violence. These details help understand the types and seriousness of crimes in different neighborhoods. Like the previous case, I might need to fix the date format, check location details, and make sure all crime categories are written consistently in accordance with Dataset 1 so the information is accurate and clear.

* Dataset 3: This dataset gives information about subway stations in New York City. It includes station IDs (GTFS Stop ID, Station ID, Complex ID), station names, and details about the subway lines that stop there. It also has geographic coordinates (latitude and longitude) to show where each station is and ADA accessibility details to indicate whether the station is accessible to people with disabilities. In the future, check location accuracy, make sure station names and routes are consistent, and fix any missing information about accessibility.

* Dataset 4: This dataset tracks how many people enter and exit the subway at different times and places. It includes station details (Station, Control Area, Unit, SCP), as well as date, time, and the number of passengers. These numbers help show how busy different stations are at different times of the day. Furthermore, the other years from 2014 to 2022 should be combined. For pre-processing, organize the time and date information correctly, remove duplicate records, and combine data from multiple turnstiles at the same station to get a full picture of station usage.

* Dataset 5: This dataset lists the Chicago ‘L’ train stops and details like Stop ID, Stop Name, and Station Name. It also shows which train lines (Red, Blue, Green, etc.) stop there. The dataset includes location coordinates (latitude and longitude) and tells whether a station is ADA accessible for people with disabilities. Station names should be written the same way across the dataset, and fix missing or incorrect information about which train lines serve each stop.

* Dataset 6: This dataset keeps track of how many people use each ‘L’ station in Chicago every day. It includes station IDs, station names, dates, and the number of riders who entered each station. There is also a day type field that shows if the data is from a weekday or weekend. I will have to convert dates into a standard format, make sure station names and IDs align with Dataset 5, and fix any missing or incorrect rider counts.

I am planning to combine these datasets by first performing a spatial join, using the coordinates of both crime incidents and transit stations to identify crimes occurring within a defined buffer or proximity around each station. Next, I would incorporate ridership data as a normalization factor—adjusting the crime counts relative to the number of people at each transit node—to better isolate the effect of the station's presence on crime rates, rather than just reflecting higher foot traffic. This integration of spatial, temporal, and ridership metrics will allow for a more nuanced analysis of how transit nodes correlate with local crime levels.

In [32]:
import numpy as np
import pandas as pd
import requests

## Dataset 1 : NYPD Arrests Data (Historic)

In [59]:
nypd = pd.read_csv("nypd.csv")
nypd["Latitude"].isna().sum()
newNypd = nypd.dropna()
print(nypd.shape, newNypd.shape)
newNypd["YEAR"] =  pd.to_datetime(newNypd['ARREST_DATE'])
newNypd['YEAR'] = newNypd['YEAR'].dt.year
print(newNypd["YEAR"].value_counts())
newNypd.head()

(5725522, 19) (5692330, 19)

C:\Users\Jongwoo\AppData\Local\Temp\ipykernel_19696\1309173052.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newNypd["YEAR"] =  pd.to_datetime(newNypd['ARREST_DATE'])
C:\Users\Jongwoo\AppData\Local\Temp\ipykernel_19696\1309173052.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newNypd['YEAR'] = newNypd['YEAR'].dt.year

2010    420555
2009    419816
2011    410938
2007    402122
2008    400272
2012    393946
2013    391586
2014    385875
2006    370773
2015    337193
2016    312403
2017    283853
2018    244198
2023    225256
2019    213089
2022    187457
2021    154011
2020    138987
Name: YEAR, dtype: int64

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lon_Lat,YEAR
0,205590989,11/24/2019,339.0,"LARCENY,PETIT FROM OPEN AREAS,",341.0,PETIT LARCENY,PL 1552500,M,M,28,0.0,25-44,F,WHITE,997571.0,234556.0,40.810476,-73.951880,POINT (-73.95188015099995 40.81047604300005),2019
1,202546976,09/17/2019,793.0,WEAPONS POSSESSION 3,118.0,DANGEROUS WEAPONS,PL 2650201,F,M,6,0.0,45-64,M,BLACK,982746.0,206647.0,40.733883,-74.005428,POINT (-74.00542831099995 40.73388303300004),2019
2,203563701,10/10/2019,494.0,"STOLEN PROPERTY 2,1,POSSESSION",111.0,POSSESSION OF STOLEN PROPERTY,PL 1654502,F,K,90,0.0,18-24,M,BLACK HISPANIC,1000830.0,197889.0,40.709829,-73.940198,POINT (-73.94019763899996 40.70982902900005),2019
3,205169609,11/14/2019,397.0,"ROBBERY,OPEN AREA UNCLASSIFIED",105.0,ROBBERY,PL 1601001,F,B,43,0.0,18-24,M,BLACK HISPANIC,1020183.0,239283.0,40.823387,-73.870170,POINT (-73.87017044999999 40.823387291000074),2019
4,204097687,10/23/2019,105.0,STRANGULATION 1ST,106.0,FELONY ASSAULT,PL 1211300,F,Q,114,0.0,25-44,M,BLACK,1007694.0,219657.0,40.769561,-73.915363,POINT (-73.91536344699995 40.769561242000066),2019

## Dataset 2 : Chicago Crimes - 2001 to Present

In [ ]:
chic = pd.read_csv("Crimes_-_2001_to_Present_20250223.csv")

# url = """https://data.cityofchicago.org/resource/ijzp-q8t2.json?$query=SELECT%0A%20%20%60id%60%2C%0A%20%20%60case_number%60%2C%0A%20%20%60date%60%2C%0A%20%20%60block%60%2C%0A%20%20%60iucr%60%2C%0A%20%20%60primary_type%60%2C%0A%20%20%60description%60%2C%0A%20%20%60location_description%60%2C%0A%20%20%60arrest%60%2C%0A%20%20%60domestic%60%2C%0A%20%20%60beat%60%2C%0A%20%20%60district%60%2C%0A%20%20%60ward%60%2C%0A%20%20%60community_area%60%2C%0A%20%20%60fbi_code%60%2C%0A%20%20%60x_coordinate%60%2C%0A%20%20%60y_coordinate%60%2C%0A%20%20%60year%60%2C%0A%20%20%60updated_on%60%2C%0A%20%20%60latitude%60%2C%0A%20%20%60longitude%60%2C%0A%20%20%60location%60%0AWHERE%0A%20%20%60date%60%0A%20%20%20%20BETWEEN%20%222015-01-01T15%3A29%3A52%22%20%3A%3A%20floating_timestamp%0A%20%20%20%20AND%20%222025-02-23T15%3A29%3A52%22%20%3A%3A%20floating_timestamp%0AORDER%20BY%20%60date%60%20DESC%20NULL%20FIRST"""
# response = requests.get(url)
# if response.status_code == 200:
#     data = response.json()
#     chicJSON = pd.DataFrame(data)
#     chicJSON.to_csv("Crimes_-_2001_to_Present_20250223.csv", index=False)
# else:
#     print("invalid response", response.status_code)

# chicJSON.head()
print(chic.shape)
chic.head()

(8261886, 22)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,13749328,JJ150135,02/15/2025 12:00:00 AM,036XX W GRAND AVE,0320,ROBBERY,STRONG ARM - NO WEAPON,GAS STATION,False,False,...,36.0,23.0,03,1152073.0,1907615.0,2025,02/22/2025 04:03:07 PM,41.902366,-87.716855,"(41.902365801, -87.716854733)"
1,13750781,JJ151388,02/15/2025 12:00:00 AM,0000X W ELM ST,0890,THEFT,FROM BUILDING,BAR OR TAVERN,False,False,...,2.0,8.0,06,1175930.0,1908090.0,2025,02/22/2025 04:03:07 PM,41.903165,-87.629210,"(41.90316534, -87.629210442)"
2,13749631,JJ150362,02/15/2025 12:00:00 AM,005XX N LECLAIRE AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,APARTMENT,False,False,...,37.0,25.0,14,1142271.0,1903044.0,2025,02/22/2025 04:03:07 PM,41.890010,-87.752973,"(41.890010091, -87.752972995)"
3,13749347,JJ150175,02/15/2025 12:00:00 AM,076XX S SAGINAW AVE,0810,THEFT,OVER $500,APARTMENT,False,False,...,7.0,43.0,06,1195249.0,1854877.0,2025,02/22/2025 04:03:07 PM,41.756690,-87.560009,"(41.756689743, -87.560008935)"
4,13749539,JJ150335,02/15/2025 12:00:00 AM,093XX S CALUMET AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,...,6.0,49.0,08B,1180225.0,1843114.0,2025,02/22/2025 04:03:07 PM,41.724768,-87.615428,"(41.724768105, -87.615428126)"

In [44]:
droppedChic = chic.dropna()
print(droppedChic.shape)
droppedChic['YEAR'] = pd.to_datetime(droppedChic["Date"])
droppedChic['YEAR'] = droppedChic["YEAR"].dt.year
droppedChic["YEAR"].value_counts()

(7554569, 22)

C:\Users\Jongwoo\AppData\Local\Temp\ipykernel_19696\3191676202.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  droppedChic['YEAR'] = pd.to_datetime(droppedChic["Date"])
C:\Users\Jongwoo\AppData\Local\Temp\ipykernel_19696\3191676202.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  droppedChic['YEAR'] = droppedChic["YEAR"].dt.year

2003    471995
2004    467139
2005    449877
2006    445514
2007    435547
2008    419656
2009    385765
2010    369778
2011    350893
2002    345045
2012    335113
2013    306368
2014    273639
2016    266494
2017    264165
2018    262915
2023    259889
2019    258172
2015    257795
2024    256289
2022    234234
2020    206935
2021    202029
2025     25425
2001      3898
Name: YEAR, dtype: int64

## Dataset 3 : MTA Subway Stations

In [ ]:
newStations = pd.read_csv("MTA_Subway_Stations.csv")
print(newStations.shape)
newStations.head()

(496, 19)

,GTFS Stop ID,Station ID,Complex ID,Division,Line,Stop Name,Borough,CBD,Daytime Routes,Structure,GTFS Latitude,GTFS Longitude,North Direction Label,South Direction Label,ADA,ADA Northbound,ADA Southbound,ADA Notes,Georeference
0,127,317,611,IRT,Broadway - 7Av,Times Sq-42 St,M,True,1 2 3,Subway,40.755290,-73.987495,Uptown,Downtown,1,1,1,NaN,POINT (-73.987495 40.75529)
1,S17,515,515,SIR,Staten Island,Annadale,SI,False,SIR,Open Cut,40.540460,-74.178217,Ferry,South Shore,0,0,0,NaN,POINT (-74.178217 40.54046)
2,S01,139,627,BMT,Franklin Shuttle,Franklin Av,Bk,False,S,Elevated,40.680596,-73.955827,Last Stop,Prospect Park,1,1,1,NaN,POINT (-73.955827 40.680596)
3,254,349,349,IRT,Eastern Pky,Junius St,Bk,False,3,Elevated,40.663515,-73.902447,Manhattan,New Lots,0,0,0,NaN,POINT (-73.902447 40.663515)
4,M01,108,108,BMT,Myrtle Av,Middle Village-Metropolitan Av,Q,False,M,Elevated,40.711396,-73.889601,Inbound,Last Stop,1,1,1,NaN,POINT (-73.889601 40.711396)

## Dataset 4 : MTA Subway Turnstile Usage Data

In [ ]:
newRidership = pd.read_csv("MTA_Subway_Turnstile_Usage_Data__2016.csv")
print(newRidership.shape)
newRidership.head()

(9492670, 11)

,C/A,Unit,SCP,Station,Line Name,Division,Date,Time,Description,Entries,Exits
0,R182,R035,00-05-00,168 ST,1AC,IRT,01/07/2016,03:00:00,REGULAR,19473975,3738151
1,R625,R062,01-06-02,CROWN HTS-UTICA,34,IRT,01/04/2016,03:00:00,REGULAR,4971017,1649564
2,N333,R141,01-00-03,FOREST HILLS 71,EFMR,IND,01/06/2016,16:00:00,REGULAR,561339,2142960
3,N305,R017,01-00-05,LEXINGTON AV/53,EM6,IND,01/04/2016,07:00:00,REGULAR,9698146,2596713
4,R238,R046,00-00-04,GRD CNTRL-42 ST,4567S,IRT,01/04/2016,15:00:00,REGULAR,21197852,10996179

## Dataset 5 : CTA - System Information - List of 'L' Stops

In [50]:
chicStations = pd.read_csv("CTA_-_System_Information_-_List_of__L__Stops.csv")
print(chicStations.shape)
chicStations.head()

(302, 17)

,STOP_ID,DIRECTION_ID,STOP_NAME,STATION_NAME,STATION_DESCRIPTIVE_NAME,MAP_ID,ADA,RED,BLUE,G,BRN,P,Pexp,Y,Pnk,O,Location
0,30082,E,Cicero (Loop-bound),Cicero,Cicero (Pink Line),40420,True,False,False,False,False,False,False,False,True,False,"(41.85182, -87.745336)"
1,30151,E,Central Park (Loop-bound),Central Park,Central Park (Pink Line),40780,True,False,False,False,False,False,False,False,True,False,"(41.853839, -87.714842)"
2,30184,W,Halsted/63rd (Ashland-bound),Halsted,Halsted (Green Line),40940,True,False,False,True,False,False,False,False,False,False,"(41.778943, -87.644244)"
3,30044,N,Cumberland (O'Hare-bound),Cumberland,Cumberland (Blue Line),40230,True,False,True,False,False,False,False,False,False,False,"(41.984246, -87.838028)"
4,30092,E,Racine (O'Hare-bound),Racine,Racine (Blue Line),40470,False,False,True,False,False,False,False,False,False,False,"(41.87592, -87.659458)"

## Dataset 6 : CTA - Ridership - 'L' Station Entries - Daily Totals

In [51]:
chicRidership = pd.read_csv("CTA_-_Ridership_-__L__Station_Entries_-_Daily_Totals.csv")
print(chicRidership.shape)
chicRidership.head()

(1250303, 5)

   station_id       stationname        date daytype  rides
0       41280    Jefferson Park  12/22/2017       W   6104
1       41000  Cermak-Chinatown  12/18/2017       W   3636
2       40280      Central-Lake  12/02/2017       A   1270
3       40140   Dempster-Skokie  12/19/2017       W   1759
4       40690          Dempster  12/03/2017       U    499

# Ethics & Privacy

This analysis will rely on publicly available data, ensuring that individual privacy is maintained throughout the whole research process. I recognize that the crime and transit datasets may contain inherent biases such as underreporting in certain cities due to varying policies or limitations in capturing the full scope of transit accessibility. To mitigate these concerns, I will ensure that I comply with the terms of use of each data source and utilize the Dean Ethics Checklist as guidance to keep us in check regarding principles such as accountability, transparency, and respect for individuals.

To address any potential biases, I could implement several strategies in this project. Firstly I will be comparing multiple data sources such as crime reports from law enforcement agencies, transit ridership data from public transportation authorities to triangulate the findings. This approach will help to identify discrepancies and improve the reliability of my analyses. Additionally, I will apply statistical techniques, such as regression modeling, to control for confounding variables and assess the robustness of the results.

Additionally, although these datasets are publicly available and fully anonymous, the inclusion of detailed geographic coordinates might lead to privacy concerns. Since spatial data can lead to inadvertent identification of individuals or communities, I must be strict about the data usage terms. To deal with this matter, I will have to further apply aggregation or anonymization techniques further into this model. In this reporting and dissemination, I will explicitly state that correlation does not imply causation, discuss the study’s limitations, and recommend that policymakers use these insights as one component within a broader framework aimed at enhancing both public safety and transit equity.

| Meeting Date  | Meeting Time| Completed Before Meeting  | Discuss at Meeting |
|---|---|---|---|
| 1/21  |  5 PM | Review expectations; brainstorm topics/questions  | Determine best form of communication (Discord); Discuss and decide on final project topic; discuss hypothesis; Start doing background research | 
| 2/4 |  5 PM |  Came up with multiple options for the final research topic and tried to narrow them down. Do background research on topic | Before choosing the final topic. I discussed pros and cons of each topic with TA. Discuss and identify potential dataset(s) and ethics; draft project proposal (on Google Docs) | 
| 2/9  | 5 PM  | Edit, finalize, and submit proposal; Search for datasets  |  Wrangling and possible analytical approaches.   |
| 2/13  | 5 PM  | Complete initial data cleaning and visualization prototypes | Review/Edit exploratory analysis results; Make Analysis Plan and hypothesis nuances  |
| 2/20  | 5 PM  | Continue detailed analysis and visualization development | Revision Analysis; Adjust analytical methods as needed; Complete project check-in |
| 3/13  | 5 PM  | Finalize analysis and draft results, conclusions, and discussion| Revision full project and prepare for final presentation |
| 3/20  | Before 11:59 PM  |  Make sure all charts and results are included and displayed properly. Finalize project report and update project website | Submit final project |